name: .NET Core Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '**/**'  # Replace with your desired .NET version (e.g., 6.0.x)

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build  # Avoid redundant build

      - name: Upload test results (optional)
        uses: actions/upload-artifact@v3
        if: always()  # Upload artifacts on all workflows
        with:
          name: test-results
          path: **/test/**.trx
